title: Tenebrous
subtitle: GloomyGhost Photo Album
auther: GloomyGhost
baseurl: "/" 
url: ""

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
repository: YuzukiHD/YuzukiHD.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

